project_id = "cpopaqguywwaqprrvony"

[functions.parse-pdf-decreto]
verify_jwt = false

[functions.process-expense-receipt]
verify_jwt = false

[functions.analyze-expense-document]
verify_jwt = false

[functions.analyze-project-document]
verify_jwt = false